name: Bit.Hub .NET Policy Harness
description: Pre/wrap/post enforcement for runner compliance (fail-open)
runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build harness
      shell: bash
      run: |
        dotnet build -c Release src/BitHub.PolicyHarness/BitHub.PolicyHarness.csproj

    - name: PRE gate
      shell: bash
      continue-on-error: true
      run: dotnet run --project src/BitHub.PolicyHarness -- pre

    # Example of wrapping a build command (optional)
    # - name: WRAP build
    #   shell: bash
    #   continue-on-error: true
    #   run: dotnet run --project src/BitHub.PolicyHarness -- wrap -- bash -lc "make build"

    - name: POST finalize
      shell: bash
      continue-on-error: true
      run: dotnet run --project src/BitHub.PolicyHarness -- post
