name: Analysis Bot

on:
  push:
    paths:
      - ".bithub-actions/manifests/master.bithub.files.yml"
      - "src/**"
  workflow_dispatch:

jobs:
  call-preflight:
    uses: ./.github/workflows/preflight.yml

  run-analysis:
    needs: call-preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run aln-analyze
        run: aln-analyze --input /github/logs --output /tmp/failure.lst --profane-allow 'fuck,shit,bitch,asshole,cunt'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          # Example: specify SDK version or leave blank to use global.json
          dotnet-version: 6.0.x
          # Optional: enable caching for NuGet packages
          cache: true
          # Optional: specify dependency lock file for cache key
          cache-dependency-path: '**/packages.lock.json'
