            - name: Setup Go environment
  uses: actions/setup-go@v5.5.0
  with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
    go-version: # optional
    # Path to the go.mod or go.work file.
    go-version-file: # optional
    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
    check-latest: # optional
    # Used to pull Go distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    cache: # optional, default is true
    # Used to specify the path to a dependency file - go.sum
    cache-dependency-path: # optional
    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
          - name: Load Bit.Hub Charter
  run: |
    test -f .bitcharter || { echo "❌ Missing .bitcharter"; exit 1; }
    cat .bitcharter

- name: Scan for disallowed terms
  run: |
    grep -R -E -i -f .bit/disallowed_terms.txt . && {
      echo "❌ Unapproved content detected. Job stopped."
      exit 1
    } || echo "✅ No disallowed content found."

- name: Verify persona registry lock
  run: |
    WANT=$(awk -F= '/^registry_sha256=/{print $2}' .bit/persona.lock)
    GOT=$(sha256sum .bit/persona_registry.json | awk '{print $1}')
    test "$WANT" = "$GOT" || { echo "❌ Persona registry hash mismatch"; exit 1; }
- name: Display Great Wall Banner
  run: |
    echo "🧱 构建合规长城: BUILDING THE GREAT WALL OF COMPLIANCE 🧱"
    echo "All runners must pass through the compliance gate."

                - name: Setup Go environment
  uses: actions/setup-go@v5.5.0
  with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
    go-version: # optional
    # Path to the go.mod or go.work file.
    go-version-file: # optional
    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
    check-latest: # optional
    # Used to pull Go distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    cache: # optional, default is true
    # Used to specify the path to a dependency file - go.sum
    cache-dependency-path: # optional
    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
          
