jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BITCOIN_TOKEN_PATH: ".bit/tokens/runner_bitcoin_token.json"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load runner .bit.coin token
        id: load_token
        run: |
          if [ ! -f "$BITCOIN_TOKEN_PATH" ]; then
            echo "::error::Runner bitcoin token missing."
            exit 1
          fi
          echo "token=$(base64 -w 0 "$BITCOIN_TOKEN_PATH")" >> "$GITHUB_OUTPUT"

      - name: Compliance check with .bit.coin
        run: |
          # TODO: Call Bit.Hub compliance API or local OPA with token and job info
          # Fail if not enough .bit.coin balance or invalid proof
          echo "Compliance check passed."

      - name: Run build steps
        run: |
          echo "Build running under Bit.Hub compliance and .bit.coin enforcement."

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          # name: my-artifact
          # artifact-ids: 12345
          # path: ./artifacts
          merge-multiple: false
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # repository: ${{ github.repository }}
          # run-id: ${{ github.run_id }}
